name: gsu_cli
description: A GSU calculator for schwab
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-53.0.dev

dependencies:
  excel: ^4.0.3

dev_dependencies:
  args: ^2.5.0
  path: ^1.9.0

dependency_overrides:
  archive: 3.6.1
